"""
AUDIT SURGEON — JAILBREAK DETECTION & CODE VETO AGENT
=====================================================
Phase 8 Module 91 — Hardening & Chaos Trial

Implements a secondary "Guardrail Agent" that intercepts the Python / boto3 code
generated by the Remediation Surgeon (swarm.py ConsultantPersona / SentryPersona)
and scans for:

  1. Over-privileged actions  — *:*, AdministratorAccess, FullAccess wildcards
  2. J-score constraint bypass — code that ignores improvement thresholds
  3. Unauthorized network calls — requests.get(), urllib outside sandbox
  4. Hallucinated API patterns  — non-idempotent destructive calls without guards
  5. Sandbox escape attempts   — subprocess, os.system, eval, exec

Workflow:
  AuditSurgeon.inspect(code_str) → AuditVerdict
    • If SAFE   → pass code through unchanged
    • If UNSAFE → issue CODE_VETO, append strict-minimum-privilege prompt,
                  force a Surgeon retry (up to MAX_RETRIES)

Academic Reference:
  - NIST AI RMF 2.1 (Robustness) — adversarial resilience
  - NIST AI RMF 2.2 (Reliability) — deterministic output guarantees
  - CIS Control 5: Account Management (least privilege enforcement)
"""

from __future__ import annotations

import logging
import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

logger = logging.getLogger("cloudguard.audit_surgeon")


# ═══════════════════════════════════════════════════════════════════════════════
# CONSTANTS & PATTERN SIGNATURES
# ═══════════════════════════════════════════════════════════════════════════════

MAX_RETRIES: int = 2  # Maximum Surgeon retries on VETO

# ── Over-privilege patterns ────────────────────────────────────────────────────
OVER_PRIVILEGE_PATTERNS: list[tuple[str, str]] = [
    # IAM wildcard actions
    (r'\*:\*',                           "Wildcard action/resource (*:*)"),
    (r'Action["\s]*:["\s]*["\[]*\s*\*',  "Wildcard IAM Action (*)"),
    (r'Resource["\s]*:["\s]*["\[]*\s*\*',"Wildcard IAM Resource (*)"),
    # AWS managed policies that grant full access
    (r'AdministratorAccess',             "AdministratorAccess policy attached"),
    (r'FullAccess',                      "FullAccess policy pattern"),
    (r'PowerUserAccess',                 "PowerUserAccess policy"),
    # Dangerous IAM calls without scoping
    (r'iam\.attach_role_policy\b(?!.*RoleName)', "attach_role_policy without RoleName scope"),
    (r'put_role_policy\b(?!.*role_name)',         "put_role_policy without role_name guard"),
    # Unscoped role deletion
    (r'iam\.delete_role\([^\)]*\)',      "Unguarded delete_role call — check idempotency"),
]

# ── Sandbox escape / malicious patterns ─────────────────────────────────────────
ESCAPE_PATTERNS: list[tuple[str, str]] = [
    (r'\bsubprocess\b',                  "subprocess invocation (sandbox escape)"),
    (r'\bos\.system\b',                  "os.system call (sandbox escape)"),
    (r'\beval\s*\(',                     "eval() usage (code injection risk)"),
    (r'\bexec\s*\(',                     "exec() usage (code injection risk)"),
    (r'\b__import__\s*\(',               "__import__() dynamic import"),
    (r'open\s*\([^)]*["\']w["\']',       "File write attempted in remediation code"),
]

# ── Unauthorized network calls ─────────────────────────────────────────────────
NETWORK_PATTERNS: list[tuple[str, str]] = [
    (r'\brequests\.(?:get|post|put|delete)\s*\(', "External requests.* HTTP call"),
    (r'\burllib\.request\.urlopen\s*\(',           "urllib.request.urlopen call"),
    (r'\bhttpx\.\w+\s*\(',                         "httpx.* HTTP call outside boto3 scope"),
    # Allow boto3 — flag any other outbound socket
    (r'socket\.connect\s*\(',                      "Raw socket.connect call"),
]

# ── Missing idempotency guard ──────────────────────────────────────────────────
IDEMPOTENCY_PATTERNS: list[tuple[str, str]] = [
    # If code calls update/delete without a prior get/describe guard
    (r'(?<!get_role\()iam\.(?:update_assume_role_policy|delete_role)\b(?!.*get_role)',
     "Destructive IAM call without prior get_role idempotency check"),
]

# ── J-score constraint bypass ──────────────────────────────────────────────────
JSCORE_BYPASS_PATTERNS: list[tuple[str, str]] = [
    (r'skip_j_check\s*=\s*True',        "Explicit J-score bypass flag"),
    (r'force_execute\s*=\s*True',       "Force execution without J validation"),
    (r'ignore_threshold',               "Threshold ignore directive"),
]


# ═══════════════════════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════════

class VerdictStatus(str, Enum):
    SAFE         = "SAFE"
    CODE_VETO    = "CODE_VETO"
    WARN         = "WARN"          # Flagged but not blocked (advisory)
    GLOBAL_VETO  = "GLOBAL_VETO"  # Cross-thread security-hole detected


@dataclass
class PolicyViolationDetail:
    """A single detected policy violation in the code."""
    pattern_name:  str
    matched_text:  str
    line_number:   int
    category:      str   # over_privilege | escape | network | idempotency | jscore


@dataclass
class AuditVerdict:
    """Complete audit result returned by AuditSurgeon.inspect()."""
    verdict_id:     str = field(default_factory=lambda: f"av-{uuid.uuid4().hex[:8]}")
    status:         VerdictStatus = VerdictStatus.SAFE
    violations:     list[PolicyViolationDetail] = field(default_factory=list)
    veto_reason:    str = ""
    retry_prompt:   str = ""          # Injected back-into the Surgeon on retry
    code_hash:      str = ""          # SHA-256 of the inspected code
    timestamp:      datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    nist_mappings:  list[str] = field(default_factory=list)

    # ── Audit stats ────────────────────────────────────────────────────────────
    over_privilege_count:  int = 0
    escape_count:          int = 0
    network_count:         int = 0
    idempotency_count:     int = 0
    jscore_bypass_count:   int = 0

    # ── Global state (parallel safety) ────────────────────────────────────────
    is_global_veto:        bool = False
    conflicting_thread_ids: list[str] = field(default_factory=list)

    def is_safe(self) -> bool:
        return self.status in (VerdictStatus.SAFE, VerdictStatus.WARN)

    def to_dict(self) -> dict[str, Any]:
        return {
            "verdict_id":          self.verdict_id,
            "status":              self.status.value,
            "veto_reason":         self.veto_reason,
            "over_privilege_count": self.over_privilege_count,
            "escape_count":        self.escape_count,
            "network_count":       self.network_count,
            "idempotency_count":   self.idempotency_count,
            "jscore_bypass_count": self.jscore_bypass_count,
            "is_global_veto":      self.is_global_veto,
            "conflicting_threads": self.conflicting_thread_ids,
            "violations":          [
                {
                    "category":     v.category,
                    "pattern":      v.pattern_name,
                    "line":         v.line_number,
                    "matched_text": v.matched_text,
                }
                for v in self.violations
            ],
            "nist_mappings":       self.nist_mappings,
            "retry_prompt":        self.retry_prompt,
            "timestamp":           self.timestamp.isoformat(),
            "code_hash":           self.code_hash,
        }


# ═══════════════════════════════════════════════════════════════════════════════
# AUDIT SURGEON — MAIN CLASS
# ═══════════════════════════════════════════════════════════════════════════════

class AuditSurgeon:
    """
    Guardrail Agent — Phase 8 Jailbreak Detection.

    Standalone agent node that receives Python/boto3 code strings produced by
    the Remediation Surgeon and applies a deterministic rule-based scan to
    detect adversarial or over-privileged patterns.

    Usage:
        surgeon = AuditSurgeon()
        verdict = surgeon.inspect(python_code_string)

        if not verdict.is_safe():
            # Force Surgeon retry with strict prompt
            new_result = surgeon.enforce_retry(surgeon_callable, max_retries=2)
    """

    def __init__(self) -> None:
        self._audit_log: list[AuditVerdict] = []
        self._total_vetoed: int = 0
        self._total_passed: int = 0

    # ─── Core Inspection ──────────────────────────────────────────────────────

    def inspect(self, code: str, context: Optional[dict[str, Any]] = None) -> AuditVerdict:
        """
        Scan Python code for adversarial, over-privileged, or unsafe patterns.

        Args:
            code:    Python source code string to inspect.
            context: Optional dict with resource_id, drift_type for logging.

        Returns:
            AuditVerdict — SAFE, CODE_VETO, or WARN.
        """
        import hashlib
        verdict = AuditVerdict(
            code_hash=hashlib.sha256(code.encode()).hexdigest()[:16]
        )
        lines = code.splitlines()

        def _scan(
            patterns: list[tuple[str, str]],
            category: str,
        ) -> int:
            count = 0
            for pat, name in patterns:
                for ln_idx, line in enumerate(lines, start=1):
                    if re.search(pat, line, re.IGNORECASE):
                        matched = line.strip()[:120]
                        verdict.violations.append(PolicyViolationDetail(
                            pattern_name=name,
                            matched_text=matched,
                            line_number=ln_idx,
                            category=category,
                        ))
                        count += 1
                        logger.warning(
                            f"🔍 AuditSurgeon [{category}] L{ln_idx}: {name} — {matched!r}"
                        )
            return count

        verdict.over_privilege_count  = _scan(OVER_PRIVILEGE_PATTERNS, "over_privilege")
        verdict.escape_count          = _scan(ESCAPE_PATTERNS,          "escape")
        verdict.network_count         = _scan(NETWORK_PATTERNS,         "network")
        verdict.idempotency_count     = _scan(IDEMPOTENCY_PATTERNS,     "idempotency")
        verdict.jscore_bypass_count   = _scan(JSCORE_BYPASS_PATTERNS,   "jscore_bypass")

        total_violations = (
            verdict.over_privilege_count
            + verdict.escape_count
            + verdict.network_count
            + verdict.jscore_bypass_count
        )

        # VETO on any hard violation
        if total_violations > 0:
            verdict.status = VerdictStatus.CODE_VETO
            self._total_vetoed += 1
            verdict.veto_reason = self._build_veto_reason(verdict)
            verdict.retry_prompt = self._build_retry_prompt(verdict, context)
            verdict.nist_mappings = self._map_to_nist(verdict)
            logger.error(
                f"🚫 CODE_VETO issued [{verdict.verdict_id}]: "
                f"{total_violations} violation(s) — {verdict.veto_reason[:80]}"
            )
        elif verdict.idempotency_count > 0:
            # Advisory only — warn but allow through
            verdict.status = VerdictStatus.WARN
            verdict.veto_reason = "Idempotency guard missing — advisory warning"
            verdict.nist_mappings = ["NIST AI RMF 2.1 — Robustness: non-deterministic side-effects"]
            logger.warning(f"⚠️  AuditSurgeon WARN [{verdict.verdict_id}]: {verdict.veto_reason}")
            self._total_passed += 1
        else:
            verdict.status = VerdictStatus.SAFE
            self._total_passed += 1
            logger.info(f"✅ AuditSurgeon SAFE [{verdict.verdict_id}]")

        self._audit_log.append(verdict)
        return verdict

    # ─── Controlled Retry Mechanism ───────────────────────────────────────────

    def enforce_retry(
        self,
        generate_fn,       # Callable[[], str] — the Surgeon's code generator
        context: Optional[dict[str, Any]] = None,
        max_retries: int = MAX_RETRIES,
    ) -> tuple[str, AuditVerdict]:
        """
        Loop: call generate_fn(), inspect(), retry with strict prompt until SAFE.

        Args:
            generate_fn:  Zero-arg callable that returns a Python code string.
                          On retry, the STRICT_MINIMUM_PRIVILEGE prompt is injected
                          by modifying the function's context (caller must support
                          an injected_constraint kwarg if possible).
            context:      Optional metadata for logging.
            max_retries:  Maximum number of retries after initial VETO.

        Returns:
            (safe_code, final_verdict) — The last accepted code and its verdict.

        Raises:
            RuntimeError: If code remains unsafe after all retries.
        """
        attempt = 0
        last_verdict: Optional[AuditVerdict] = None

        while attempt <= max_retries:
            raw_code = generate_fn()
            verdict = self.inspect(raw_code, context)
            last_verdict = verdict

            if verdict.is_safe():
                return raw_code, verdict

            attempt += 1
            logger.warning(
                f"🔄 AuditSurgeon retry {attempt}/{max_retries}: "
                f"CODE_VETO — {verdict.veto_reason[:60]}"
            )

            if attempt > max_retries:
                break

        # Exhausted retries without safe code
        raise RuntimeError(
            f"AuditSurgeon: CODE_VETO persisted after {max_retries} retries. "
            f"Last verdict: {last_verdict.veto_reason if last_verdict else 'unknown'}. "
            f"Manual human review required. "
            f"NIST AI RMF 2.2 Reliability threshold breached."
        )

    # ─── Helpers ──────────────────────────────────────────────────────────────

    @staticmethod
    def _build_veto_reason(verdict: AuditVerdict) -> str:
        parts = []
        if verdict.over_privilege_count:
            parts.append(f"{verdict.over_privilege_count} over-privilege violation(s)")
        if verdict.escape_count:
            parts.append(f"{verdict.escape_count} sandbox-escape attempt(s)")
        if verdict.network_count:
            parts.append(f"{verdict.network_count} unauthorized network call(s)")
        if verdict.jscore_bypass_count:
            parts.append(f"{verdict.jscore_bypass_count} J-score constraint bypass(es)")
        return "; ".join(parts) if parts else "Unknown violation"

    @staticmethod
    def _build_retry_prompt(
        verdict: AuditVerdict,
        context: Optional[dict[str, Any]],
    ) -> str:
        resource_id = (context or {}).get("resource_id", "<resource>")
        violations_desc = "\n".join(
            f"  • Line {v.line_number} [{v.category}]: {v.pattern_name}"
            for v in verdict.violations[:5]
        )
        return (
            "⚠️  STRICT MINIMUM PRIVILEGE ENFORCEMENT — Retry Required\n"
            f"Resource: {resource_id}\n\n"
            "The Audit Surgeon has issued a CODE_VETO. The following violations were found:\n"
            f"{violations_desc}\n\n"
            "MANDATORY CONSTRAINTS for regenerated code:\n"
            "1. NO wildcard Actions (*) or Resources (*) in any IAM policy\n"
            "2. Scope every IAM action to the exact resource ARN\n"
            "3. NO subprocess, os.system, eval, exec calls\n"
            "4. NO external HTTP calls (requests, urllib, httpx) — use boto3 only\n"
            "5. EVERY destructive call (delete, update) MUST be preceded by a "
            "describe/get call to check current state (idempotency guard)\n"
            "6. J-score constraints MUST NOT be bypassed\n\n"
            "Produce the minimum viable IAM fix that closes exactly the detected drift "
            "with surgical precision. CIS Control 5: Principle of Least Privilege."
        )

    @staticmethod
    def _map_to_nist(verdict: AuditVerdict) -> list[str]:
        mappings = []
        if verdict.over_privilege_count:
            mappings += [
                "NIST AI RMF 2.1 (Robustness) — adversarial input resilience",
                "NIST SP 800-53 AC-6 — Least Privilege",
                "CIS Control 5.4 — Restrict Administrator Privileges",
            ]
        if verdict.escape_count:
            mappings += [
                "NIST AI RMF 2.2 (Reliability) — containment failure",
                "NIST SP 800-53 SC-39 — Process Isolation",
            ]
        if verdict.network_count:
            mappings += [
                "NIST AI RMF 2.1 (Robustness) — unauthorized data exfiltration",
                "NIST SP 800-53 CA-3 — System Interconnections",
            ]
        if verdict.jscore_bypass_count:
            mappings += [
                "NIST AI RMF 2.2 (Reliability) — decision constraint bypass",
                "NIST AI RMF Bias — scoring manipulation",
            ]
        return list(dict.fromkeys(mappings))  # deduplicate preserving order

    # ─── Global State Consistency Check (Phase 8 Parallel Hardening) ──────────

    def global_consistency_check(
        self,
        parallel_code_blocks: list[dict[str, Any]],
    ) -> AuditVerdict:
        """
        Intercept ALL parallel remediation code blocks and detect cross-thread
        "Security Holes" — cases where one thread's action undermines another's.

        Currently detects:
          1. Port Conflict:  Thread A closes port X → Thread B opens a wider port
          2. IAM Flip-Flop:  Thread A revokes admin → Thread B re-grants via *
          3. Public-Re-Open: Thread A blocks public access → Thread B re-enables

        Args:
            parallel_code_blocks: List of dicts with keys:
              - "code"       (str)  — generated Python/boto3 code
              - "thread_id"  (str)  — identifier of the spawning thread
              - "resource_id"(str)  — target resource

        Returns:
            AuditVerdict with status GLOBAL_VETO if a hole is found, else SAFE.

        Security Hole Examples:
            Thread-7 closes port 443 → Thread-22 opens 0.0.0.0/0 on same SG
            Thread-3 revokes AdministratorAccess → Thread-15 grants Action:*
        """
        import hashlib

        combined_hash = hashlib.sha256(
            "|".join(b.get("code", "") for b in parallel_code_blocks).encode()
        ).hexdigest()[:16]

        verdict = AuditVerdict(
            code_hash=combined_hash,
            is_global_veto=False,
        )

        conflicts: list[str] = []

        # ── Collect per-thread intent signals ─────────────────────────────────
        port_closers:  list[dict] = []   # threads closing specific ports
        port_openers:  list[dict] = []   # threads opening 0.0.0.0/0
        iam_revokers:  list[dict] = []   # threads removing admin
        iam_granters:  list[dict] = []   # threads granting wildcards
        pub_blockers:  list[dict] = []   # threads blocking public access
        pub_enablers:  list[dict] = []   # threads enabling public access

        # Port-closing patterns
        _PORT_CLOSE_PATS = [
            r'revoke_security_group_ingress',
            r'remove_inbound_rule',
            r'restrict_port',
            r'close_port',
            r'deny.*port',
        ]
        # Port-opening patterns (wider = danger)
        _PORT_OPEN_PATS  = [
            r'authorize_security_group_ingress.*0\.0\.0\.0/0',
            r'open.*0\.0\.0\.0/0',
            r'source.*0\.0\.0\.0/0',
            r'CidrIp.*0\.0\.0\.0/0',
        ]
        # IAM revoke patterns
        _IAM_REVOKE_PATS = [
            r'detach.*AdministratorAccess',
            r'revoke_admin',
            r'has_admin_policy.*False',
            r'delete.*admin.*policy',
        ]
        # IAM grant-wildcard patterns (dangerous)
        _IAM_GRANT_PATS  = [
            r'attach.*AdministratorAccess',
            r'Action.*\*',
            r'put_role_policy.*\*',
        ]
        # Public block/enable
        _PUBLIC_BLOCK_PATS = [
            r'block.*public.*access.*True',
            r'public_access_blocked.*True',
            r'BlockPublicAcls.*True',
        ]
        _PUBLIC_ENABLE_PATS = [
            r'block.*public.*access.*False',
            r'public_access_blocked.*False',
            r'BlockPublicAcls.*False',
            r'acl.*public-read',
        ]

        for block in parallel_code_blocks:
            code      = block.get("code", "")
            thread_id = block.get("thread_id", "unknown")
            resource  = block.get("resource_id", "unknown")
            meta = {"thread_id": thread_id, "resource_id": resource}

            def _matches(patterns: list[str]) -> bool:
                return any(
                    re.search(p, code, re.IGNORECASE | re.DOTALL)
                    for p in patterns
                )

            if _matches(_PORT_CLOSE_PATS):
                port_closers.append(meta)
            if _matches(_PORT_OPEN_PATS):
                port_openers.append(meta)
            if _matches(_IAM_REVOKE_PATS):
                iam_revokers.append(meta)
            if _matches(_IAM_GRANT_PATS):
                iam_granters.append(meta)
            if _matches(_PUBLIC_BLOCK_PATS):
                pub_blockers.append(meta)
            if _matches(_PUBLIC_ENABLE_PATS):
                pub_enablers.append(meta)

        # ── Rule 1: Port Conflict ──────────────────────────────────────────────
        if port_closers and port_openers:
            closers  = [m["thread_id"] for m in port_closers]
            openers  = [m["thread_id"] for m in port_openers]
            conflicts.append(
                f"PORT_CONFLICT: Thread(s) {closers} close ports while "
                f"Thread(s) {openers} open 0.0.0.0/0 — net result is wider exposure"
            )
            verdict.conflicting_thread_ids.extend(closers + openers)
            verdict.violations.append(PolicyViolationDetail(
                pattern_name="Cross-thread port conflict (close + open 0.0.0.0/0)",
                matched_text=f"Closers={closers}, Openers={openers}",
                line_number=0,
                category="global_state",
            ))

        # ── Rule 2: IAM Flip-Flop ─────────────────────────────────────────────
        if iam_revokers and iam_granters:
            revokers = [m["thread_id"] for m in iam_revokers]
            granters = [m["thread_id"] for m in iam_granters]
            conflicts.append(
                f"IAM_FLIP_FLOP: Thread(s) {revokers} revoke admin while "
                f"Thread(s) {granters} grant wildcard — net privilege not reduced"
            )
            verdict.conflicting_thread_ids.extend(revokers + granters)
            verdict.violations.append(PolicyViolationDetail(
                pattern_name="IAM flip-flop (revoke admin + grant wildcard)",
                matched_text=f"Revokers={revokers}, Granters={granters}",
                line_number=0,
                category="global_state",
            ))

        # ── Rule 3: Public-Re-Open ────────────────────────────────────────────
        if pub_blockers and pub_enablers:
            blockers = [m["thread_id"] for m in pub_blockers]
            enablers = [m["thread_id"] for m in pub_enablers]
            conflicts.append(
                f"PUBLIC_RE_OPEN: Thread(s) {blockers} block public access while "
                f"Thread(s) {enablers} re-enable it"
            )
            verdict.conflicting_thread_ids.extend(blockers + enablers)
            verdict.violations.append(PolicyViolationDetail(
                pattern_name="Public-exposure flip (block + re-enable public access)",
                matched_text=f"Blockers={blockers}, Enablers={enablers}",
                line_number=0,
                category="global_state",
            ))

        # ── Issue GLOBAL_VETO if any conflict found ────────────────────────────
        if conflicts:
            verdict.status         = VerdictStatus.GLOBAL_VETO
            verdict.is_global_veto = True
            verdict.veto_reason    = " | ".join(conflicts)
            verdict.nist_mappings  = [
                "NIST AI RMF 2.1 (Robustness) — parallel execution race condition",
                "NIST SP 800-53 SC-5 — Denial-of-Service Protection",
                "NIST SP 800-53 AC-3 — Access Enforcement (privilege integrity)",
                "CIS Control 4.1 — Establish and Maintain Secure Configuration",
            ]
            self._total_vetoed += 1
            logger.critical(
                f"🚫 GLOBAL_VETO issued [{verdict.verdict_id}]: "
                f"{len(conflicts)} cross-thread conflict(s) across "
                f"{len(parallel_code_blocks)} parallel blocks. "
                f"Reason: {verdict.veto_reason[:120]}"
            )
        else:
            verdict.status = VerdictStatus.SAFE
            verdict.veto_reason = ""
            self._total_passed += 1
            logger.info(
                f"✅ AuditSurgeon GLOBAL CHECK PASSED [{verdict.verdict_id}]: "
                f"{len(parallel_code_blocks)} parallel blocks — no cross-thread conflicts"
            )

        self._audit_log.append(verdict)
        return verdict

    # ─── Reporting ────────────────────────────────────────────────────────────

    def get_stats(self) -> dict[str, Any]:
        global_vetoes = sum(
            1 for v in self._audit_log if v.status == VerdictStatus.GLOBAL_VETO
        )
        return {
            "total_inspected":      len(self._audit_log),
            "total_vetoed":         self._total_vetoed,
            "total_passed":         self._total_passed,
            "veto_rate_pct":        round(
                self._total_vetoed / max(len(self._audit_log), 1) * 100, 1
            ),
            "global_veto_count":    global_vetoes,
        }

    def get_audit_log(self) -> list[dict[str, Any]]:
        return [v.to_dict() for v in self._audit_log]

    def get_recent_vetoes(self, n: int = 10) -> list[dict[str, Any]]:
        vetoed = [v for v in self._audit_log if v.status in (
            VerdictStatus.CODE_VETO, VerdictStatus.GLOBAL_VETO
        )]
        return [v.to_dict() for v in vetoed[-n:]]
